# Generated by Django 6.0 on 2025-12-14 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetflixTitle',
            fields=[
                ('show_id', models.CharField(help_text='Unique identifier for this title', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('Movie', 'Movie'), ('TV Show', 'TV Show')], help_text='Type of content: Movie or TV Show', max_length=20)),
                ('title', models.CharField(help_text='Title of the movie or TV show', max_length=250, validators=[django.core.validators.MinLengthValidator(1)])),
                ('director', models.CharField(blank=True, help_text='Director(s) - comma-separated if multiple', max_length=250, null=True)),
                ('cast', models.TextField(blank=True, help_text='Cast members - comma-separated list', null=True)),
                ('country', models.CharField(blank=True, help_text='Country/countries of production - comma-separated if multiple', max_length=150, null=True)),
                ('date_added', models.DateField(blank=True, help_text='Date when content was added to Netflix', null=True)),
                ('release_year', models.IntegerField(help_text='Original release year of the content', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('rating', models.CharField(blank=True, help_text='Content rating (e.g., TV-MA, PG-13, R)', max_length=10, null=True)),
                ('duration', models.CharField(help_text='Duration - minutes for movies, seasons for TV shows', max_length=20)),
                ('listed_in', models.TextField(help_text='Genres/categories - comma-separated list', validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(help_text='Brief description or synopsis', validators=[django.core.validators.MinLengthValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in our database')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'Netflix Title',
                'verbose_name_plural': 'Netflix Titles',
                'ordering': ['-date_added', '-release_year'],
                'indexes': [models.Index(fields=['type'], name='api_netflix_type_dde3b7_idx'), models.Index(fields=['release_year'], name='api_netflix_release_647f00_idx'), models.Index(fields=['date_added'], name='api_netflix_date_ad_240fa0_idx'), models.Index(fields=['rating'], name='api_netflix_rating_d1bf75_idx')],
            },
        ),
    ]
