# Generated by Django 6.0 on 2025-12-26 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetflixTitle',
            fields=[
                ('show_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('Movie', 'Movie'), ('TV Show', 'TV Show')], max_length=20)),
                ('title', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(1)])),
                ('director', models.CharField(blank=True, max_length=250, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.CharField(max_length=20)),
                ('listed_in', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Netflix Title',
                'verbose_name_plural': 'Netflix Titles',
                'ordering': ['-date_added', '-release_year'],
            },
        ),
    ]
