# Generated by Django 6.0 on 2025-12-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='netflixtitle',
            name='api_netflix_type_dde3b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='netflixtitle',
            name='api_netflix_release_647f00_idx',
        ),
        migrations.RemoveIndex(
            model_name='netflixtitle',
            name='api_netflix_date_ad_240fa0_idx',
        ),
        migrations.RemoveIndex(
            model_name='netflixtitle',
            name='api_netflix_rating_d1bf75_idx',
        ),
    ]
